brew "exiftool"
brew "ffmpeg", args: [
    "--with-fdk-aac",
    "--with-fontconfig",
    "--with-freetype",
    "--with-libass",
    "--with-libbluray",
    "--with-libvidstab",
    "--with-libvorbis",
    "--with-libvpx",
    "--with-opencore-amr",
    "--with-openh264",
    "--with-openjpeg",
    "--with-opus",
    "--with-rubberband",
    "--with-schroedinger",
    "--with-tesseract",
    "--with-theora",
    "--with-tools",
    "--with-wavpack",
    "--with-webp",
    "--with-x265",
    "--with-xz",
    "--with-zimg"
]
# Bundled with ffmpeg
## brew "vid.stab" # https://git.io/vQ0SA
